
-- Drop table

-- DROP TABLE public.contato;

CREATE TABLE public.contato (
	id int8 NOT NULL,
	email varchar(255) NULL,
	nome varchar(255) NULL,
	CONSTRAINT contato_pkey PRIMARY KEY (id)
);


INSERT INTO public.contato
(id, email, nome)
VALUES(208, 'admin@admin.com', 'Mariana');
INSERT INTO public.contato
(id, email, nome)
VALUES(209, 'admin@admin.com', 'Mariana');
INSERT INTO public.contato
(id, email, nome)
VALUES(204, 'eduardo.delfino@zup.com.br', 'Eduardo');
INSERT INTO public.contato
(id, email, nome)
VALUES(206, 'admin@admin.com', 'Adriana');
INSERT INTO public.contato
(id, email, nome)
VALUES(210, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(211, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(212, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(213, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(214, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(215, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(216, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(217, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(218, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(219, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(220, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(221, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(222, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(223, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(224, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(225, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(226, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(227, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(228, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(229, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(230, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(231, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(232, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(233, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(234, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(235, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(236, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(237, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(238, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(239, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(240, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(241, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(242, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(243, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(244, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(245, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(246, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(247, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(248, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(249, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(250, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(251, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(252, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(253, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(254, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(255, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(256, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(257, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(258, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(259, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(260, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(261, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(262, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(263, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(264, 'eduardo.delfino@gmail.com', 'Rodrigues');
INSERT INTO public.contato
(id, email, nome)
VALUES(265, 'eduardo.delfino@gmail.com', 'Rodrigues');
